export { LogoIcon } from "./logo";
export { Icon1 } from "./logo copy";
export { Icon10 } from "./logo copy 10";
export { Icon11 } from "./logo copy 11";
export { Icon12 } from "./logo copy 12";
export { Icon2 } from "./logo copy 2";
export { Icon3 } from "./logo copy 3";
export { Icon4 } from "./logo copy 4";
export { Icon5 } from "./logo copy 5";
export { Icon6 } from "./logo copy 6";
export { Icon7 } from "./logo copy 7";
export { Icon8 } from "./logo copy 8";
export { Icon9 } from "./logo copy 9";
export { NotificationIcon } from "./NoticeIcon";
export { PlusIcon } from "./PlusIcon";
export { QuestionIcon } from "./QuestionIcon";
export { SearchIcon } from "./SearchIcon";
export { SettingIcon } from "./SettingIcon";
export { UserIcon } from "./UserIcon";
export { FacebookIcon } from "./FacebookIcon";
export { GoogleIcon } from "./GoogleIcon";
export { ArowIcon } from "./ArowIcon";
export { EditIcon } from "./EditIcon";
export { RemoveIcon } from "./RemoveIcon";
export { ContactIcon } from "./ContactIcon";
export { OpportunitiesIcon } from "./OpportunitieIcon";
export { TaskIcon } from "./TaskIcon";
export { EmailIcon } from "./EmailIcon";
export { PhoneIcon } from "./PhoneIcon";
export { MenuIcon } from "./MenuIcon";
export { CloseIcon } from "./CloseIcon";
export { TagIcon } from "./TagIcon";
